# Generated by Django 3.0.7 on 2020-07-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefLabel', models.CharField(max_length=100)),
                ('identifier', models.URLField(verbose_name='Identifier')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='km', max_length=6, verbose_name='Unit')),
            ],
        ),
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_access_point', models.BooleanField()),
                ('is_preferred_access_point', models.BooleanField(verbose_name='Is Preferred Access Point')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='Headline (Brief Description)')),
                ('same_as', models.URLField(blank=True, null=True, verbose_name='Same As')),
            ],
        ),
        migrations.CreateModel(
            name='KnownRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonAndOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
            ],
        ),
        migrations.CreateModel(
            name='RiskMitigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RiskModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RouteAccessRestrictionTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_access_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RouteDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefLabel', models.CharField(max_length=100, verbose_name='Route Designation Term')),
                ('description', models.CharField(max_length=250)),
                ('url', models.URLField(verbose_name='Formal Definition URL')),
            ],
        ),
        migrations.CreateModel(
            name='RouteGuide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('url', models.URLField(verbose_name='Trackback URL')),
                ('date_published', models.DateField(blank=True, verbose_name='Date Published')),
                ('date_modified', models.DateField(blank=True, verbose_name='Date Modified')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='Headline (Brief Description)')),
                ('is_loop', models.BooleanField(default=True, verbose_name='Is Loop')),
                ('id_as_url', models.URLField(verbose_name='ID (URL)')),
                ('activity', models.ManyToManyField(to='protoroute.Activity')),
                ('author', models.ManyToManyField(to='protoroute.PersonAndOrganization', verbose_name='Author')),
                ('end_point', models.ManyToManyField(blank=True, to='protoroute.EndPoint')),
            ],
        ),
        migrations.CreateModel(
            name='RouteGuideSegment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('url', models.URLField(verbose_name='Trackback URL')),
                ('date_published', models.DateField(blank=True, verbose_name='Date Published')),
                ('date_modified', models.DateField(blank=True, verbose_name='Date Modified')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='Headline (Brief Description)')),
                ('is_loop', models.BooleanField(default=True, verbose_name='Is Loop')),
                ('id_as_url', models.URLField(verbose_name='ID (URL)')),
                ('sequence', models.IntegerField(verbose_name='Segment Number')),
                ('activity', models.ManyToManyField(to='protoroute.Activity')),
                ('additional_info', models.ManyToManyField(to='protoroute.Article')),
                ('author', models.ManyToManyField(to='protoroute.PersonAndOrganization', verbose_name='Author')),
                ('end_point', models.ManyToManyField(blank=True, to='protoroute.EndPoint')),
            ],
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_access_point', models.BooleanField()),
                ('is_preferred_access_point', models.BooleanField(verbose_name='Is Preferred Access Point')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='Headline (Brief Description)')),
                ('same_as', models.URLField(blank=True, null=True, verbose_name='Same As')),
            ],
        ),
        migrations.CreateModel(
            name='StartPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_access_point', models.BooleanField()),
                ('is_preferred_access_point', models.BooleanField(verbose_name='Is Preferred Access Point')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='Headline (Brief Description)')),
                ('same_as', models.URLField(blank=True, null=True, verbose_name='Same As')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_verified', models.DateField(verbose_name='Date Verified')),
                ('route_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg_verification_record', to='protoroute.RouteGuide')),
                ('route_guide_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_verification_record', to='protoroute.RouteGuideSegment')),
                ('verified_by', models.ManyToManyField(to='protoroute.PersonAndOrganization', verbose_name='Verified By')),
            ],
        ),
        migrations.CreateModel(
            name='UserGeneratedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spatial_coverage', models.CharField(max_length=500)),
                ('associated_media', models.CharField(max_length=500)),
                ('accountable_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protoroute.PersonAndOrganization')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='protoroute.PersonAndOrganization')),
            ],
        ),
        migrations.CreateModel(
            name='TransportNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_mode', models.CharField(choices=[('Bus', 'Bus'), ('Rail', 'Rail'), ('Road', 'Road'), ('Foot', 'Foot'), ('Bicycle', 'Bicycle')], max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('routepoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_transport_note', to='protoroute.RoutePoint')),
            ],
        ),
        migrations.CreateModel(
            name='RouteSegmentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_as_url', models.URLField(verbose_name='@id')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('alternatives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seg_route_segment_group', to='protoroute.RouteSegmentGroup', verbose_name='Alternative Group To')),
                ('segments', models.ManyToManyField(related_name='rg_route_segment_group', to='protoroute.RouteGuideSegment', verbose_name='Includes Segments')),
            ],
        ),
        migrations.CreateModel(
            name='RouteRiskAdvisory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_description', models.CharField(max_length=250)),
                ('user_safety_feedback', models.CharField(max_length=500)),
                ('is_maintained', models.BooleanField()),
                ('risk_information_url', models.URLField()),
                ('traffic_description', models.CharField(max_length=500)),
                ('known_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.KnownRisk')),
                ('maintained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintains', to='protoroute.PersonAndOrganization', verbose_name='Is Maintained By')),
                ('risk_mitigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.RiskMitigator')),
                ('risk_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.RiskModifier')),
                ('route_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg_risk_advisory', to='protoroute.RouteGuide')),
                ('route_guide_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_risk_advisory', to='protoroute.RouteGuideSegment')),
            ],
        ),
        migrations.CreateModel(
            name='RouteLegalAdvisory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('legal_defurl', models.URLField(verbose_name='Legal Definition URL')),
                ('route_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protoroute.RouteDesignation', verbose_name='Route Designation')),
                ('route_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg_legal_advisory', to='protoroute.RouteGuide')),
                ('route_guide_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_legal_advisory', to='protoroute.RouteGuideSegment')),
            ],
        ),
        migrations.AddField(
            model_name='routeguidesegment',
            name='point_of_interest',
            field=models.ManyToManyField(blank=True, to='protoroute.RoutePoint'),
        ),
        migrations.AddField(
            model_name='routeguidesegment',
            name='route_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_route_guide', to='protoroute.RoutePoint'),
        ),
        migrations.AddField(
            model_name='routeguidesegment',
            name='start_point',
            field=models.ManyToManyField(blank=True, to='protoroute.StartPoint'),
        ),
        migrations.AddField(
            model_name='routeguide',
            name='point_of_interest',
            field=models.ManyToManyField(blank=True, to='protoroute.RoutePoint'),
        ),
        migrations.AddField(
            model_name='routeguide',
            name='start_point',
            field=models.ManyToManyField(blank=True, to='protoroute.StartPoint'),
        ),
        migrations.CreateModel(
            name='RouteGradient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_gradient', models.CharField(default='0%', max_length=10)),
                ('avg_gradient', models.CharField(default='0%', max_length=10)),
                ('gradient_term', models.CharField(max_length=100, verbose_name='Gradient Term')),
                ('gradient_defurl', models.URLField(verbose_name='Gradient Definition URL')),
                ('description', models.CharField(max_length=250)),
                ('route_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg_gradient', to='protoroute.RouteGuide')),
                ('route_guide_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_gradient', to='protoroute.RouteGuideSegment')),
                ('total_elevation_gain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_elevation_gain', to='protoroute.Distance')),
                ('total_elevation_loss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_elevation_loss', to='protoroute.Distance')),
            ],
        ),
        migrations.CreateModel(
            name='RouteDifficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_term', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=250)),
                ('difficulty_defurl', models.URLField(verbose_name='Difficulty Definition URL')),
                ('route_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg_difficulty', to='protoroute.RouteGuide')),
                ('route_guide_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_difficulty', to='protoroute.RouteGuideSegment')),
            ],
        ),
        migrations.AddField(
            model_name='routedesignation',
            name='route_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg_route_designation', to='protoroute.RouteGuide'),
        ),
        migrations.AddField(
            model_name='routedesignation',
            name='route_guide_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_route_designation', to='protoroute.RouteGuideSegment'),
        ),
        migrations.CreateModel(
            name='RouteAccessRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('route_access_restriction_information_url', models.URLField()),
                ('route_access_restriction_timespan', models.CharField(max_length=50)),
                ('route_access_restriction_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.RouteAccessRestrictionTerm')),
                ('route_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg_access_restriction', to='protoroute.RouteGuide')),
                ('route_guide_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_access_restriction', to='protoroute.RouteGuideSegment')),
            ],
        ),
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provenance_url', models.URLField()),
                ('version', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.PersonAndOrganization')),
                ('route_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg_provenance', to='protoroute.RouteGuide')),
                ('route_guide_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_provenance', to='protoroute.RouteGuideSegment')),
            ],
        ),
        migrations.CreateModel(
            name='MapReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_series', models.CharField(max_length=10)),
                ('map_number', models.CharField(max_length=10)),
                ('grid_reference', models.CharField(max_length=10)),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='protoroute.PersonAndOrganization', verbose_name='publisher')),
                ('routepoint', models.ManyToManyField(related_name='rp_mapref', to='protoroute.RoutePoint')),
            ],
        ),
        migrations.CreateModel(
            name='MapImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_type', models.CharField(choices=[('RouteMap', 'RouteMap'), ('ElevationMap', 'ElevationMap'), ('CustomMap', 'CustomMap')], max_length=12)),
                ('image', models.URLField()),
                ('encoding_format', models.CharField(max_length=40)),
                ('route_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg_mapimage', to='protoroute.RouteGuide')),
                ('route_guide_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_mapimage', to='protoroute.RouteGuideSegment')),
            ],
        ),
        migrations.CreateModel(
            name='IndicativeDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=10, verbose_name='Duration (8601)')),
                ('route_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg_duration', to='protoroute.RouteGuide')),
                ('route_guide_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_duration', to='protoroute.RouteGuideSegment')),
            ],
        ),
        migrations.CreateModel(
            name='GeoPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_type', models.CharField(choices=[('RouteMap', 'RouteMap'), ('ElevationMap', 'ElevationMap'), ('CustomMap', 'CustomMap')], max_length=12)),
                ('url', models.URLField()),
                ('encoding_format', models.CharField(max_length=40)),
                ('route_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg_geopath', to='protoroute.RouteGuide')),
                ('route_guide_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_geopath', to='protoroute.RouteGuideSegment')),
            ],
        ),
        migrations.CreateModel(
            name='GeoCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Post Code')),
                ('routepoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_geo', to='protoroute.RoutePoint')),
            ],
        ),
        migrations.AddField(
            model_name='distance',
            name='route_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg_distance', to='protoroute.RouteGuide'),
        ),
        migrations.AddField(
            model_name='distance',
            name='route_guide_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_distance', to='protoroute.RouteGuideSegment'),
        ),
        migrations.CreateModel(
            name='AmenityFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('routepoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_amenity', to='protoroute.RoutePoint')),
            ],
        ),
        migrations.CreateModel(
            name='AccessibilityDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('route_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg_access_description', to='protoroute.RouteGuide')),
                ('route_guide_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_access_description', to='protoroute.RouteGuideSegment')),
            ],
        ),
    ]
