# Generated by Django 3.0.7 on 2020-07-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protoroute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeguide',
            name='accessibility_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.AccessibilityDescription'),
        ),
    ]
