# Generated by Django 3.0.7 on 2020-06-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protoroute', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personandorganization',
            name='map_reference',
        ),
        migrations.RemoveField(
            model_name='personandorganization',
            name='route_risk_advisory',
        ),
        migrations.AddField(
            model_name='mapreference',
            name='map_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='protoroute.PersonAndOrganization', verbose_name='publisher'),
        ),
        migrations.AddField(
            model_name='routeriskadvisory',
            name='maintained_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintains', to='protoroute.PersonAndOrganization', verbose_name='Is Maintained By'),
        ),
    ]
