# Generated by Django 3.0.7 on 2020-07-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoroute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provenance',
            name='provenance_url',
            field=models.URLField(verbose_name='Provenance'),
        ),
    ]
