# Generated by Django 3.0.7 on 2020-06-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protoroute', '0002_auto_20200623_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapreference',
            old_name='map_reference',
            new_name='publisher',
        ),
        migrations.RemoveField(
            model_name='accessibilitydescription',
            name='route_guide',
        ),
        migrations.RemoveField(
            model_name='accessibilitydescription',
            name='route_guide_segment',
        ),
        migrations.RemoveField(
            model_name='amenityfeature',
            name='route_point',
        ),
        migrations.RemoveField(
            model_name='distance',
            name='route_point',
        ),
        migrations.RemoveField(
            model_name='geocoordinates',
            name='route_point',
        ),
        migrations.RemoveField(
            model_name='geopath',
            name='route_guide',
        ),
        migrations.RemoveField(
            model_name='geopath',
            name='route_guide_segment',
        ),
        migrations.RemoveField(
            model_name='knownrisk',
            name='rra',
        ),
        migrations.RemoveField(
            model_name='mapimage',
            name='route_guide',
        ),
        migrations.RemoveField(
            model_name='mapimage',
            name='route_guide_segment',
        ),
        migrations.RemoveField(
            model_name='mapreference',
            name='route_point',
        ),
        migrations.RemoveField(
            model_name='riskmitigator',
            name='rra',
        ),
        migrations.RemoveField(
            model_name='riskmodifier',
            name='rra',
        ),
        migrations.RemoveField(
            model_name='routeaccessrestriction',
            name='route_guide',
        ),
        migrations.RemoveField(
            model_name='routeaccessrestriction',
            name='route_guide_segment',
        ),
        migrations.RemoveField(
            model_name='routeaccessrestrictionterm',
            name='rar',
        ),
        migrations.RemoveField(
            model_name='routegradient',
            name='route_guide',
        ),
        migrations.RemoveField(
            model_name='routegradient',
            name='route_guide_segment',
        ),
        migrations.RemoveField(
            model_name='routelegaladvisory',
            name='route_guide',
        ),
        migrations.RemoveField(
            model_name='routelegaladvisory',
            name='route_guide_segment',
        ),
        migrations.RemoveField(
            model_name='routepoint',
            name='route_guide',
        ),
        migrations.RemoveField(
            model_name='routepoint',
            name='route_guide_segment',
        ),
        migrations.RemoveField(
            model_name='routeriskadvisory',
            name='route_guide',
        ),
        migrations.RemoveField(
            model_name='routeriskadvisory',
            name='route_guide_segment',
        ),
        migrations.RemoveField(
            model_name='transportnote',
            name='route_point',
        ),
        migrations.AddField(
            model_name='routeaccessrestriction',
            name='route_access_restriction_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.RouteAccessRestrictionTerm'),
        ),
        migrations.AddField(
            model_name='routeguide',
            name='accessibility_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_description', to='protoroute.AccessibilityDescription'),
        ),
        migrations.AddField(
            model_name='routeguide',
            name='end_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_point', to='protoroute.RoutePoint'),
        ),
        migrations.AddField(
            model_name='routeguide',
            name='geo_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_path', to='protoroute.GeoPath'),
        ),
        migrations.AddField(
            model_name='routeguide',
            name='map_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_image', to='protoroute.MapImage'),
        ),
        migrations.AddField(
            model_name='routeguide',
            name='point_of_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_of_interest', to='protoroute.RoutePoint'),
        ),
        migrations.AddField(
            model_name='routeguide',
            name='route_access_restriction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_access_restriction', to='protoroute.RouteAccessRestriction'),
        ),
        migrations.AddField(
            model_name='routeguide',
            name='route_gradient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_gradient', to='protoroute.RouteGradient'),
        ),
        migrations.AddField(
            model_name='routeguide',
            name='route_legal_advisory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_legal_advisory', to='protoroute.RouteLegalAdvisory'),
        ),
        migrations.AddField(
            model_name='routeguide',
            name='route_risk_advisory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_risk_advisory', to='protoroute.RouteRiskAdvisory'),
        ),
        migrations.AddField(
            model_name='routeguide',
            name='start_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_point', to='protoroute.RoutePoint'),
        ),
        migrations.AddField(
            model_name='routeguidesegment',
            name='accessibility_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_accessibility_description', to='protoroute.AccessibilityDescription'),
        ),
        migrations.AddField(
            model_name='routeguidesegment',
            name='end_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_end_point', to='protoroute.RoutePoint'),
        ),
        migrations.AddField(
            model_name='routeguidesegment',
            name='geo_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_geo_path', to='protoroute.GeoPath'),
        ),
        migrations.AddField(
            model_name='routeguidesegment',
            name='map_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_map_image', to='protoroute.MapImage'),
        ),
        migrations.AddField(
            model_name='routeguidesegment',
            name='point_of_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_point_of_interest', to='protoroute.RoutePoint'),
        ),
        migrations.AddField(
            model_name='routeguidesegment',
            name='route_access_restriction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_route_access_restriction', to='protoroute.RouteAccessRestriction'),
        ),
        migrations.AddField(
            model_name='routeguidesegment',
            name='route_gradient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_route_gradient', to='protoroute.RouteGradient'),
        ),
        migrations.AddField(
            model_name='routeguidesegment',
            name='route_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_route_guide', to='protoroute.RoutePoint'),
        ),
        migrations.AddField(
            model_name='routeguidesegment',
            name='route_legal_advisory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_route_legal_advisory', to='protoroute.RouteLegalAdvisory'),
        ),
        migrations.AddField(
            model_name='routeguidesegment',
            name='route_risk_advisory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_route_risk_advisory', to='protoroute.RouteRiskAdvisory'),
        ),
        migrations.AddField(
            model_name='routeguidesegment',
            name='start_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_start_point', to='protoroute.RoutePoint'),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='amenity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.AmenityFeature'),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='geo_coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.GeoCoordinates'),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='mapref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.MapReference', verbose_name='Map Reference'),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='transport_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.TransportNote'),
        ),
        migrations.AddField(
            model_name='routeriskadvisory',
            name='known_risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.KnownRisk'),
        ),
        migrations.AddField(
            model_name='routeriskadvisory',
            name='risk_mitigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.RiskMitigator'),
        ),
        migrations.AddField(
            model_name='routeriskadvisory',
            name='risk_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protoroute.RiskModifier'),
        ),
        migrations.AlterField(
            model_name='routeguide',
            name='distance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elevation', to='protoroute.Distance'),
        ),
        migrations.AlterField(
            model_name='routeguide',
            name='route_difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_difficulty', to='protoroute.RouteDifficulty'),
        ),
        migrations.AlterField(
            model_name='routeguide',
            name='verification_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_record', to='protoroute.VerificationRecord'),
        ),
        migrations.AlterField(
            model_name='routeguidesegment',
            name='distance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_elevation', to='protoroute.Distance'),
        ),
        migrations.AlterField(
            model_name='routeguidesegment',
            name='route_difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_route_difficulty', to='protoroute.RouteDifficulty'),
        ),
        migrations.AlterField(
            model_name='routeguidesegment',
            name='verification_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_verification_record', to='protoroute.VerificationRecord'),
        ),
    ]
