# Generated by Django 3.0.7 on 2020-07-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protoroute', '0002_auto_20200723_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeguide',
            name='is_based_on',
        ),
        migrations.AddField(
            model_name='provenance',
            name='route_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg_provenance', to='protoroute.RouteGuide'),
        ),
        migrations.AddField(
            model_name='provenance',
            name='route_guide_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_provenance', to='protoroute.RouteGuide'),
        ),
    ]
