# Generated by Django 3.0.7 on 2020-06-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoroute', '0003_auto_20200623_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routepoint',
            name='same_as',
            field=models.URLField(blank=True, null=True, verbose_name='Same As'),
        ),
    ]
