# Generated by Django 3.0.7 on 2020-06-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoroute', '0004_auto_20200623_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportnote',
            name='transport_mode',
            field=models.CharField(max_length=100),
        ),
    ]
