# Generated by Django 3.0.7 on 2020-07-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protoroute', '0004_auto_20200724_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routepoint',
            name='geo_coordinates',
        ),
        migrations.RemoveField(
            model_name='routepoint',
            name='mapref',
        ),
        migrations.AddField(
            model_name='geocoordinates',
            name='routepoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_geo', to='protoroute.RoutePoint'),
        ),
        migrations.AddField(
            model_name='mapreference',
            name='routepoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_mapref', to='protoroute.RoutePoint', verbose_name='Map Reference'),
        ),
        migrations.AlterField(
            model_name='amenityfeature',
            name='routepoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_amenity', to='protoroute.RoutePoint'),
        ),
        migrations.AlterField(
            model_name='transportnote',
            name='routepoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_transport_note', to='protoroute.RoutePoint'),
        ),
    ]
