# Generated by Django 3.0.7 on 2020-07-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoroute', '0005_auto_20200724_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapreference',
            name='routepoint',
        ),
        migrations.AddField(
            model_name='mapreference',
            name='routepoint',
            field=models.ManyToManyField(related_name='rp_mapref', to='protoroute.RoutePoint'),
        ),
    ]
