# Generated by Django 3.0.7 on 2020-06-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoroute', '0005_auto_20200623_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportnote',
            name='transport_mode',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Rail', 'Rail'), ('Road', 'Road'), ('Foot', 'Foot'), ('Bicycle', 'Bicycle')], max_length=100),
        ),
    ]
