# Generated by Django 3.0.7 on 2020-07-24 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protoroute', '0006_auto_20200724_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicativeduration',
            name='route_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg_duration', to='protoroute.RouteGuide'),
        ),
        migrations.AddField(
            model_name='indicativeduration',
            name='route_guide_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_duration', to='protoroute.RouteGuideSegment'),
        ),
        migrations.AlterField(
            model_name='accessibilitydescription',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
