# Generated by Django 3.0.7 on 2020-07-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protoroute', '0006_auto_20200623_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routeguidesegment',
            old_name='segment',
            new_name='sequence',
        ),
        migrations.AddField(
            model_name='routeguide',
            name='segments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='protoroute.RouteGuideSegment'),
        ),
    ]
