# Generated by Django 3.0.7 on 2020-07-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protoroute', '0007_auto_20200703_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routeguide',
            old_name='segments',
            new_name='segment',
        ),
    ]
