# Generated by Django 3.0.7 on 2020-07-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoroute', '0008_auto_20200703_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routedesignation',
            old_name='route_des_term',
            new_name='prefLabel',
        ),
        migrations.RemoveField(
            model_name='routeguidesegment',
            name='top_level_route_guide',
        ),
        migrations.AddField(
            model_name='geocoordinates',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Post Code'),
        ),
        migrations.AddField(
            model_name='routeguidesegment',
            name='author',
            field=models.ManyToManyField(to='protoroute.PersonAndOrganization', verbose_name='Author'),
        ),
    ]
